export const CREATE_OFFERS_LIST_ITEM = 'fetchList/CREATE_OFFERS_LIST_ITEM';
export const READ_OFFERS_LIST_ITEM = 'fetchList/READ_OFFERS_LIST_ITEM';
export const UPDATE_OFFERS_LIST_ITEM = 'fetchList/UPDATE_OFFERS_LIST_ITEM';
export const DELETE_OFFERS_LIST_ITEM = 'fetchList/DELETE_OFFERS_LIST_ITEM';